# ==== CONFIGURE =====
# Use a Node 18 base image because is (LTS)
FROM node:18 as builder
# Set the working directory to /app inside the container
WORKDIR /app
# Copy app files
COPY ./ ./

# ==== BUILD =====
ARG BUILD_MODE="development"
# Install dependencies
RUN npm install
# Build the app
RUN npm run $BUILD_MODE

# ==== NOT WORK === ERROR tsc not found Because typescript dont installed
# Build the app
# RUN tsc
# In mode development | testing | production
# RUN vite build --mode development

# === BUNDLE ===
# Bundle static assets with nginx
FROM nginx:1.21.0-alpine as production
# Copy built assets from `builder` image
COPY --from=builder /app/dist /usr/share/nginx/html
# Add your nginx.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Expose port
EXPOSE 80
# Start nginx
CMD ["nginx", "-g", "daemon off;"]
