version: "3.9"
services:
  client:
    image: client-eco
    build: 
      context: ./client
      dockerfile: Dockerfile-nginx
      args:
        - BUILD_MODE=build-production
    depends_on:
      - server
    ports:
      - 3000:80
  
  server:
    image: server-eco
    build: 
      context: ./server
      dockerfile: Dockerfile
      args:
        - ENV_MODE=production
    environment:
      - ENV_MODE=production
    ports:
      - "4000:4000"
    command: npm run start:production