# Por ahora docker-compose-full-development.yaml es lo mismo que /docker-composes/hmr/docker-compose.override.yaml con la 
# combinación client => development npm run start:development server => development development npm run start:development

version: "3.9"
services:
  client:
    image: client-eco
    build: 
      context: ./client
      dockerfile: Dockerfile
      args:
        - ENV_MODE=development
    depends_on:
      - server
    ports:
      - 3000:3500
    volumes:
      - ./client/src:/app/src
    command: npm run start:development
    restart: always
  
  server:
    image: server-eco
    build: 
      context: ./server
      dockerfile: Dockerfile
      args:
        - ENV_MODE=development
    environment:
      - ENV_MODE=development
    ports:
      - "4000:4000"
    volumes:
      - ./server/src:/app/src
    command: npm run start:development
    restart: always